#!/bin/bash
sed -i "s/REACT_APP_FIREBASE_API_KEY/$FB_API_KEY/g; s/REACT_APP_FIREBASE_AUTH_DOMAIN/$FB_AUTH_DOMAIN/g; s/REACT_APP_FIREBASE_PROJECT_ID/$FB_PROJECT_ID/g; s/REACT_APP_FIREBASE_STORAGE_BUCKET/$FB_STORAGE_BUCKET/g; s/REACT_APP_FIREBASE_MESSAGING_SENDER_ID/$FB_MESSAGING_SENDER_ID/g; s/REACT_APP_FIREBASE_APP_ID/$FB_APP_ID/g" index.html
